import type { Metadata } from 'next';

import { BRAND } from '@/lib/brand';

const SUPPORT_EMAIL = 'support@sozoplay.com';

const GOVERNING_LAW = 'England and Wales, United Kingdom';

function getSiteOrigin(): string {
  const raw = process.env.NEXT_PUBLIC_APP_URL?.trim();
  if (!raw) return 'https://sozoplay.com';
  try {
    const withProtocol = /^https?:\/\//i.test(raw) ? raw : `https://${raw}`;
    return new URL(withProtocol).origin;
  } catch {
    return 'https://sozoplay.com';
  }
}

const linkClass =
  'font-medium text-primary underline-offset-2 transition-colors hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50 focus-visible:ring-offset-2 rounded-sm';

export const metadata: Metadata = {
  title: `Terms of Service | ${BRAND.productName}`,
  description: `Terms of Service for ${BRAND.productName}.`,
};

export default function TermsPage() {
  const siteOrigin = getSiteOrigin();

  return (
    <main className="mx-auto max-w-4xl px-6 py-16 text-neutral-800">
      <h1 className="mb-6 text-3xl font-bold text-neutral-900">
        Terms of Service
      </h1>

      <p className="mb-6">Last updated: April 10, 2026</p>

      <p className="mb-6">
        Please read these Terms of Service (&quot;Terms&quot;) carefully before using
        the website and related services operated by <strong>Sozo Play</strong>{' '}
        (&quot;us,&quot; &quot;we,&quot; or &quot;our&quot;) and available at{' '}
        <a href={siteOrigin} className={linkClass}>
          {siteOrigin}
        </a>{' '}
        (the &quot;Service&quot;). The Service includes audio storytelling and
        listening features, as well as tools that use artificial intelligence to
        assist with creative writing and story creation where we make those
        features available.
      </p>

      <p className="mb-10">
        By accessing or using the Service, you agree to be bound by these Terms. If
        you disagree with any part of the Terms, you may not access the Service.
      </p>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold text-neutral-900">
          1. Description of Service
        </h2>
        <p>
          Sozo Play provides a platform designed to assist users with creative
          writing, storytelling, and audio listening experiences. Parts of the Service
          utilize third-party Large Language Models (LLMs) and related services to
          process user prompts and generate text or other content in authorized
          workflows.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold text-neutral-900">
          2. User Accounts
        </h2>
        <p>
          When you create an account with us, you must provide information that is
          accurate, complete, and current at all times. You are responsible for
          safeguarding the password that you use to access the Service and for any
          activities or actions under your account.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold text-neutral-900">3. Content</h2>
        <p className="mb-4">
          <strong>Your Content:</strong> You retain ownership of the text inputs
          (prompts) and the final stories or other creative materials you create using
          the Service, subject to the license below and applicable law.
        </p>
        <p className="mb-4">
          <strong>AI-Generated Content:</strong> To the extent permitted by law, we
          claim no ownership over the outputs generated by the AI based on your
          prompts. However, you acknowledge that AI-generated content may be similar
          or identical across different users.
        </p>
        <p>
          <strong>License to Us:</strong> By using the Service, you grant us a
          worldwide, non-exclusive, royalty-free license to host, store, and process
          your content solely for the purpose of providing and improving the
          Service.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold text-neutral-900">
          4. Acceptable Use Policy
        </h2>
        <p className="mb-4">You agree not to use the Service to:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            Generate content that is illegal, harmful, threatening, abusive,
            harassing, defamatory, or otherwise objectionable.
          </li>
          <li>
            Create content that infringes on the intellectual property rights of
            others.
          </li>
          <li>
            Attempt to &quot;jailbreak,&quot; reverse engineer, or bypass the safety
            filters of the underlying AI models or our integrations.
          </li>
          <li>
            Use the Service to generate automated spam or deceptive content intended
            to mislead others.
          </li>
          <li>
            Use the Service for any purpose that violates the policies of our
            third-party providers (for example, hosting or infrastructure providers
            such as <strong>Vercel</strong>, AI routing or model providers such as{' '}
            <strong>OpenRouter</strong> and underlying model vendors, payment
            processors such as <strong>Stripe</strong>, or authentication providers
            where applicable).
          </li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold text-neutral-900">
          5. Disclaimer of AI Accuracy
        </h2>
        <p className="mb-4">You understand and agree that:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            The Service provides AI-generated content for creative and entertainment
            purposes.
          </li>
          <li>
            <strong>&quot;Hallucinations&quot;:</strong> AI may generate information
            that is factually incorrect, biased, or nonsensical.
          </li>
          <li>
            We do not guarantee the accuracy, completeness, or usefulness of any
            AI-generated output. You should not rely on the Service for professional,
            legal, medical, or financial advice.
          </li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold text-neutral-900">
          6. Intellectual Property
        </h2>
        <p>
          The Service and its original content (excluding content provided by users),
          features, and functionality are and will remain the exclusive property of
          Sozo Play and its licensors. Our trademarks and trade dress may not be used
          in connection with any product or service without our prior written
          consent.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold text-neutral-900">7. Termination</h2>
        <p>
          We may terminate or suspend your account and bar access to the Service
          immediately, without prior notice or liability, under our sole discretion,
          for any reason whatsoever, including without limitation if you breach the
          Terms.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold text-neutral-900">
          8. Limitation of Liability
        </h2>
        <p className="mb-4">
          In no event shall Sozo Play, nor its directors, employees, or partners, be
          liable for any indirect, incidental, special, consequential, or punitive
          damages, including without limitation, loss of profits, data, use, or other
          intangible losses, resulting from:
        </p>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            Your access to or use of (or inability to access or use) the Service.
          </li>
          <li>Any content obtained from the Service.</li>
          <li>
            Unauthorized access, use, or alteration of your transmissions or
            content.
          </li>
        </ul>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold text-neutral-900">
          9. &quot;As Is&quot; Disclaimer
        </h2>
        <p>
          Your use of the Service is at your sole risk. The Service is provided on an
          &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. The Service is
          provided without warranties of any kind, whether express or implied.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold text-neutral-900">
          10. Governing Law
        </h2>
        <p>
          These Terms shall be governed and construed in accordance with the laws of{' '}
          {GOVERNING_LAW}, without regard to its conflict of law provisions.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="mb-3 text-xl font-semibold text-neutral-900">11. Changes</h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these
          Terms at any time. We will provide at least 30 days&apos; notice prior to
          any new terms taking effect. What constitutes a material change will be
          determined at our sole discretion.
        </p>
      </section>

      <section>
        <h2 className="mb-3 text-xl font-semibold text-neutral-900">12. Contact Us</h2>
        <p className="mb-4">
          If you have any questions about these Terms, please contact us at:
        </p>
        <ul className="list-none space-y-2 p-0">
          <li>
            Email:{' '}
            <a href={`mailto:${SUPPORT_EMAIL}`} className={linkClass}>
              {SUPPORT_EMAIL}
            </a>
          </li>
          <li>
            Website:{' '}
            <a href={siteOrigin} className={linkClass}>
              {siteOrigin}
            </a>
          </li>
        </ul>
      </section>
    </main>
  );
}
