import type { GenerationCatalogItem, ToolFamilyMap } from '@/lib/generation/types';

export const GENERATION_TOOL_FAMILY: ToolFamilyMap = {
  story_studio_generate_brief: 'text',
  story_studio_generate_script: 'text',
  story_studio_generate_episode: 'text',
  story_studio_generate_cover: 'image',
  blog_generate_text: 'text',
  blog_generate_image: 'image',
  story_studio_narration: 'audio_narration',
};

export const BUILT_IN_GENERATION_CATALOG: GenerationCatalogItem[] = [
  {
    id: 'text-openrouter-nvidia-nemotron-3-super-free',
    family: 'text',
    provider: 'openrouter',
    providerLabel: 'OpenRouter',
    vendorLabel: 'NVIDIA',
    kind: 'model',
    value: 'nvidia/nemotron-3-super:free',
    label: 'Nemotron 3 Super free',
    envKeyRequired: 'OPENROUTER_API_KEY',
    supportsManualEntry: true,
    isDefault: true,
    sortOrder: 10,
  },
  {
    id: 'text-openrouter-anthropic-claude-opus-4-7',
    family: 'text',
    provider: 'openrouter',
    providerLabel: 'OpenRouter',
    vendorLabel: 'Anthropic',
    kind: 'model',
    value: 'anthropic/claude-opus-4.7',
    label: 'Claude Opus 4.7',
    envKeyRequired: 'OPENROUTER_API_KEY',
    supportsManualEntry: true,
    sortOrder: 20,
  },
  {
    id: 'text-openai-gpt-5-4',
    family: 'text',
    provider: 'openai',
    providerLabel: 'OpenAI',
    vendorLabel: 'OpenAI',
    kind: 'model',
    value: 'gpt-5.4',
    label: 'GPT-5.4',
    envKeyRequired: 'OPENAI_API_KEY',
    isDefault: true,
    sortOrder: 30,
  },
  {
    id: 'image-openrouter-google-nano-banana',
    family: 'image',
    provider: 'openrouter',
    providerLabel: 'OpenRouter',
    vendorLabel: 'Google',
    kind: 'model',
    value: 'google/gemini-2.5-flash-image',
    label: 'Nano Banana',
    envKeyRequired: 'OPENROUTER_API_KEY',
    supportsManualEntry: true,
    isDefault: true,
    sortOrder: 10,
  },
  {
    id: 'image-openrouter-openai-gpt-5-image',
    family: 'image',
    provider: 'openrouter',
    providerLabel: 'OpenRouter',
    vendorLabel: 'OpenAI',
    kind: 'model',
    value: 'openai/gpt-5-image',
    label: 'GPT-5 Image',
    envKeyRequired: 'OPENROUTER_API_KEY',
    supportsManualEntry: true,
    sortOrder: 20,
  },
  {
    id: 'audio-elevenlabs-arabella',
    family: 'audio_narration',
    provider: 'elevenlabs',
    providerLabel: 'ElevenLabs',
    vendorLabel: 'ElevenLabs',
    kind: 'voice',
    value: 'Z3R5wn05IrDiVCyEkUrK',
    label: 'Arabella - Mysterious and Emotive Arabella',
    envKeyRequired: 'ELEVENLABS_API_KEY',
    isDefault: true,
    sortOrder: 10,
  },
];
